# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-05-14 12:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='comments',
            new_name='comment',
        ),
    ]
